//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Order = new HashSet<Order>();
        }
    
        public System.Guid Guid { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string Photo { get; set; }
        public Nullable<int> YearProduction { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Mileage { get; set; }
        public Nullable<int> Status { get; set; }
        public string Mark { get; set; }
        public string Type { get; set; }
        public string City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
